# Copyright (C) 2025 ArmaVita LLC
# SPDX-License-Identifier: AGPL-3.0-only

"""Partnership Ads — branded-content ad permissions on the Instagram User node.

In v25 the `branded_content_ad_permissions` edge lives on the Instagram
professional-account (IG User) node — NOT the Business or Page node (both return
Graph error 100 for this edge), matching the Business SDK's
IGUser.get/create_branded_content_ad_permissions bindings.
"""


import json
from typing import Any, Dict, Optional

from .graph_client import make_api_request, meta_api_tool
from .mcp_runtime import mcp_server
from mcp.types import ToolAnnotations


def _json(payload: Dict[str, Any]) -> str:
    return json.dumps(payload, indent=2)


@mcp_server.tool(annotations=ToolAnnotations(readOnlyHint=True, openWorldHint=True))
@meta_api_tool
async def list_branded_content_ad_permissions(
    instagram_user_id: str,
    creator_username: Optional[str] = None,
    meta_access_token: Optional[str] = None,
    page_size: int = 25,
    page_cursor: str = "",
) -> str:
    """List the creators authorized to run partnership/branded-content ads for an IG account.

    `instagram_user_id` is the advertiser's Instagram professional-account (IG User)
    id — this edge does NOT exist on the Business or Page node. `creator_username`
    filters to one creator. Use the returned ids/handles when building partnership
    ad creatives (source_instagram_media_id on the creative).
    """
    if not str(instagram_user_id or "").strip():
        return _json({"error": "instagram_user_id is required (the IG professional-account id)"})

    params: Dict[str, Any] = {"page_size": int(page_size)}
    if page_cursor:
        params["page_cursor"] = page_cursor
    if creator_username:
        params["creator_username"] = str(creator_username).strip()

    payload = await make_api_request(
        f"{str(instagram_user_id).strip()}/branded_content_ad_permissions",
        meta_access_token,
        params,
    )
    return _json(payload)


@mcp_server.tool(annotations=ToolAnnotations(readOnlyHint=False, destructiveHint=False, idempotentHint=False, openWorldHint=True))
@meta_api_tool
async def grant_branded_content_ad_permission(
    instagram_user_id: str,
    permission_data: Dict[str, Any],
    meta_access_token: Optional[str] = None,
) -> str:
    """Grant a creator branded-content ad permission on an IG professional account.

    POSTs to `/{instagram_user_id}/branded_content_ad_permissions` (the real,
    SDK-confirmed write edge — there is no `partnership_ad_codes` edge). This is the
    programmatic basis for partnership ads. `permission_data` is sent verbatim and
    typically includes the creator identifier (e.g. `{"creator_username": "..."}`).
    NOTE: consumer-facing "partnership ad codes" are generated by the creator in the
    Instagram/Facebook app and consumed in the creative via source_instagram_media_id;
    they are not minted via this API.
    """
    if not str(instagram_user_id or "").strip():
        return _json({"error": "instagram_user_id is required (the IG professional-account id)"})
    if not permission_data:
        return _json({"error": "permission_data is required"})

    payload = await make_api_request(
        f"{str(instagram_user_id).strip()}/branded_content_ad_permissions",
        meta_access_token,
        permission_data,
        method="POST",
    )
    return _json(payload)
