# Copyright (C) 2025 ArmaVita LLC
# SPDX-License-Identifier: AGPL-3.0-only

import ast
from pathlib import Path


def _tool_signature_map() -> dict[str, list[str]]:
    core_dir = Path(__file__).resolve().parents[1] / "src" / "armavita_meta_ads_mcp" / "core"
    signatures: dict[str, list[str]] = {}
    for path in sorted(core_dir.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if not isinstance(node, ast.AsyncFunctionDef):
                continue
            is_tool = False
            for decorator in node.decorator_list:
                if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute):
                    if decorator.func.attr == "tool":
                        is_tool = True
                        break
            if not is_tool:
                continue
            signatures[node.name] = [arg.arg for arg in node.args.args if arg.arg != "self"]
    return signatures


def test_v1_tool_names_are_exact():
    signatures = _tool_signature_map()
    assert set(signatures) == {
        "apply_recommendation",
        "batch_products",
        "clone_ad",
        "clone_ad_creative",
        "clone_ad_set",
        "clone_campaign",
        "create_ad",
        "create_ad_creative",
        "create_ad_set",
        "create_campaign",
        "create_campaign_budget_schedule",
        "create_custom_audience",
        "create_custom_conversion",
        "create_insights_job",
        "create_lookalike_audience",
        "create_reach_frequency_prediction",
        "create_report",
        "create_threads_account",
        "delete_custom_audience",
        "delete_custom_conversion",
        "estimate_audience_size",
        "export_ad_image_file",
        "get_account_controls",
        "get_threads_account",
        "grant_branded_content_ad_permission",
        "list_account_pages",
        "list_ad_accounts",
        "list_ad_creatives",
        "list_ad_custom_derived_metrics",
        "list_ad_images",
        "list_ad_previews",
        "list_ad_sets",
        "list_ad_videos",
        "list_ads",
        "list_branded_content_ad_permissions",
        "list_business_datasets",
        "list_campaigns",
        "list_custom_audiences",
        "list_custom_conversions",
        "list_insights",
        "list_product_catalogs",
        "list_product_sets",
        "list_products",
        "list_reach_frequency_predictions",
        "list_recommendations",
        "manage_custom_audience_users",
        "read_ad",
        "read_ad_account",
        "read_ad_creative",
        "read_ad_image",
        "read_ad_set",
        "read_campaign",
        "read_custom_audience",
        "read_custom_conversion",
        "read_dataset_quality",
        "read_insights_job",
        "read_insights_job_results",
        "read_reach_frequency_prediction",
        "read_web_content",
        "search_ads_archive",
        "search_behaviors",
        "search_demographics",
        "search_geo_locations",
        "search_interests",
        "search_pages",
        "search_web_content",
        "send_capi_events",
        "suggest_interests",
        "update_account_controls",
        "update_ad",
        "update_ad_creative",
        "update_ad_set",
        "update_campaign",
        "update_custom_audience",
        "update_custom_conversion",
        "upload_ad_image_asset",
        "upload_ad_video_asset",
        "upsert_product",
    }


def test_v1_signature_snapshot():
    signatures = _tool_signature_map()
    assert signatures == {'apply_recommendation': ['object_id', 'recommendation_data', 'meta_access_token'],
 'batch_products': ['product_catalog_id', 'requests', 'meta_access_token', 'allow_upsert'],
 'clone_ad': ['ad_id',
              'meta_access_token',
              'target_ad_set_id',
              'name_suffix',
              'clone_ad_creative',
              'new_creative_name',
              'new_status'],
 'clone_ad_creative': ['ad_creative_id',
                       'meta_access_token',
                       'name_suffix',
                       'new_primary_text',
                       'new_headline',
                       'new_description',
                       'new_cta_type',
                       'new_destination_url'],
 'clone_ad_set': ['ad_set_id',
                  'meta_access_token',
                  'target_campaign_id',
                  'name_suffix',
                  'include_ads',
                  'include_creatives',
                  'new_daily_budget',
                  'new_targeting',
                  'new_status'],
 'clone_campaign': ['campaign_id',
                    'meta_access_token',
                    'name_suffix',
                    'include_ad_sets',
                    'include_ads',
                    'include_creatives',
                    'copy_schedule',
                    'new_daily_budget',
                    'new_status',
                    'migrate_to_advantage_plus'],
 'create_ad': ['ad_account_id',
               'name',
               'ad_set_id',
               'ad_creative_id',
               'status',
               'bid_amount',
               'tracking_specs',
               'conversion_domain',
               'meta_access_token'],
 'create_ad_creative': ['ad_account_id',
                        'ad_image_hash',
                        'meta_access_token',
                        'name',
                        'facebook_page_id',
                        'link_url',
                        'primary_text',
                        'primary_text_variants',
                        'headline_text',
                        'headline_variants',
                        'description_text',
                        'description_variants',
                        'ad_image_hashes',
                        'ad_video_id',
                        'thumbnail_url',
                        'optimization_type',
                        'dynamic_creative_spec',
                        'call_to_action_type',
                        'lead_form_id',
                        'instagram_user_id',
                        'threads_user_id',
                        'ad_formats',
                        'asset_customization_rules',
                        'destination_spec',
                        'degrees_of_freedom_spec',
                        'creative_features_spec',
                        'carousel_cards',
                        'product_set_id',
                        'url_tags'],
 'create_ad_set': ['ad_account_id',
                   'campaign_id',
                   'name',
                   'optimization_goal',
                   'billing_event',
                   'status',
                   'daily_budget',
                   'lifetime_budget',
                   'targeting',
                   'bid_amount',
                   'bid_strategy',
                   'bid_constraints',
                   'start_time',
                   'end_time',
                   'dsa_beneficiary',
                   'promoted_object',
                   'destination_type',
                   'is_dynamic_creative',
                   'placement_soft_opt_out',
                   'attribution_spec',
                   'frequency_control_specs',
                   'dsa_payor',
                   'meta_access_token'],
 'create_campaign': ['ad_account_id',
                     'name',
                     'objective',
                     'meta_access_token',
                     'status',
                     'special_ad_categories',
                     'daily_budget',
                     'lifetime_budget',
                     'buying_type',
                     'bid_strategy',
                     'bid_cap',
                     'spend_cap',
                     'campaign_budget_optimization',
                     'ab_test_control_setups',
                     'use_ad_set_level_budgets',
                     'is_adset_budget_sharing_enabled',
                     'special_ad_category_country',
                     'apply_default_budget',
                     'bid_constraints',
                     'smart_promotion_type'],
 'create_campaign_budget_schedule': ['campaign_id',
                                     'budget_value',
                                     'budget_value_type',
                                     'time_start',
                                     'time_end',
                                     'meta_access_token'],
 'create_custom_audience': ['ad_account_id',
                            'name',
                            'subtype',
                            'meta_access_token',
                            'description',
                            'customer_file_source',
                            'rule',
                            'rule_aggregation',
                            'retention_days'],
 'create_custom_conversion': ['ad_account_id',
                              'name',
                              'event_source_id',
                              'rule',
                              'custom_event_type',
                              'meta_access_token',
                              'description',
                              'advanced_rule',
                              'action_source_type',
                              'default_conversion_value'],
 'create_insights_job': ['object_id',
                         'meta_access_token',
                         'date_range',
                         'breakdown',
                         'breakdowns',
                         'action_breakdowns',
                         'summary_action_breakdowns',
                         'level',
                         'fields',
                         'action_attribution_windows',
                         'export_format'],
 'create_lookalike_audience': ['ad_account_id',
                               'name',
                               'origin_audience_id',
                               'lookalike_spec',
                               'meta_access_token',
                               'description'],
 'create_reach_frequency_prediction': ['ad_account_id', 'prediction', 'meta_access_token'],
 'create_report': ['ad_account_id',
                   'meta_access_token',
                   'report_type',
                   'date_range',
                   'campaign_ids',
                   'export_format',
                   'report_name',
                   'include_sections',
                   'breakdowns',
                   'action_breakdowns',
                   'summary_action_breakdowns',
                   'comparison_period',
                   'action_attribution_windows'],
 'create_threads_account': ['instagram_user_id', 'facebook_page_id', 'mode', 'meta_access_token'],
 'delete_custom_audience': ['custom_audience_id', 'meta_access_token'],
 'delete_custom_conversion': ['custom_conversion_id', 'meta_access_token'],
 'estimate_audience_size': ['meta_access_token',
                            'ad_account_id',
                            'targeting',
                            'optimization_goal',
                            'interest_list',
                            'interest_fbid_list'],
 'export_ad_image_file': ['ad_id', 'meta_access_token', 'output_dir'],
 'get_account_controls': ['ad_account_id', 'meta_access_token'],
 'get_threads_account': ['instagram_user_id', 'facebook_page_id', 'mode', 'meta_access_token'],
 'list_account_pages': ['ad_account_id', 'meta_access_token'],
 'list_ad_accounts': ['meta_access_token', 'meta_user_id', 'page_size', 'page_cursor'],
 'list_ad_creatives': ['ad_id', 'meta_access_token', 'page_cursor'],
 'list_ad_custom_derived_metrics': ['ad_account_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_ad_images': ['ad_account_id', 'meta_access_token', 'page_size', 'page_cursor', 'hashes'],
 'list_ad_previews': ['ad_id', 'meta_access_token', 'ad_format', 'locale', 'render_type', 'width', 'height'],
 'list_ad_sets': ['ad_account_id', 'meta_access_token', 'page_size', 'campaign_id', 'page_cursor'],
 'list_ad_videos': ['ad_account_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_ads': ['ad_account_id', 'meta_access_token', 'page_size', 'campaign_id', 'ad_set_id', 'page_cursor'],
 'grant_branded_content_ad_permission': ['instagram_user_id', 'permission_data', 'meta_access_token'],
 'list_branded_content_ad_permissions': ['instagram_user_id',
                                         'creator_username',
                                         'meta_access_token',
                                         'page_size',
                                         'page_cursor'],
 'list_business_datasets': ['business_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_campaigns': ['ad_account_id',
                    'meta_access_token',
                    'page_size',
                    'status_filter',
                    'objective_filter',
                    'page_cursor'],
 'list_custom_audiences': ['ad_account_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_custom_conversions': ['ad_account_id', 'meta_access_token', 'page_size', 'page_cursor', 'fields'],
 'list_insights': ['object_id',
                   'meta_access_token',
                   'date_range',
                   'breakdown',
                   'breakdowns',
                   'action_breakdowns',
                   'summary_action_breakdowns',
                   'level',
                   'page_size',
                   'page_cursor',
                   'action_attribution_windows',
                   'compact',
                   'fields'],
 'list_product_catalogs': ['business_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_product_sets': ['product_catalog_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_products': ['product_catalog_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'list_reach_frequency_predictions': ['ad_account_id', 'meta_access_token', 'page_size', 'page_cursor', 'fields'],
 'list_recommendations': ['object_id', 'meta_access_token'],
 'manage_custom_audience_users': ['custom_audience_id',
                                  'operation',
                                  'schema',
                                  'data',
                                  'meta_access_token',
                                  'auto_hash',
                                  'app_ids',
                                  'page_ids'],
 'read_ad': ['ad_id', 'meta_access_token'],
 'read_ad_account': ['ad_account_id', 'meta_access_token'],
 'read_ad_creative': ['ad_creative_id', 'meta_access_token'],
 'read_ad_image': ['ad_id', 'meta_access_token'],
 'read_ad_set': ['ad_set_id', 'meta_access_token'],
 'read_campaign': ['campaign_id', 'meta_access_token'],
 'read_custom_audience': ['custom_audience_id', 'meta_access_token'],
 'read_custom_conversion': ['custom_conversion_id', 'meta_access_token', 'fields'],
 'read_dataset_quality': ['dataset_id', 'meta_access_token'],
 'read_insights_job': ['report_run_id', 'meta_access_token'],
 'read_insights_job_results': ['report_run_id', 'meta_access_token', 'page_size', 'page_cursor'],
 'read_reach_frequency_prediction': ['rf_prediction_id', 'meta_access_token', 'fields'],
 'read_web_content': ['resource_id'],
 'search_ads_archive': ['ad_reached_countries',
                        'search_terms',
                        'meta_access_token',
                        'ad_type',
                        'page_size',
                        'page_cursor',
                        'fields',
                        'ad_active_status',
                        'ad_delivery_date_min',
                        'ad_delivery_date_max',
                        'search_page_ids',
                        'search_type',
                        'languages',
                        'media_type',
                        'publisher_platforms'],
 'search_behaviors': ['meta_access_token', 'page_size', 'page_cursor'],
 'search_demographics': ['meta_access_token', 'demographic_class', 'page_size', 'page_cursor'],
 'search_geo_locations': ['query', 'meta_access_token', 'location_types', 'page_size', 'page_cursor'],
 'search_interests': ['query', 'meta_access_token', 'page_size', 'page_cursor'],
 'search_pages': ['ad_account_id', 'meta_access_token', 'query'],
 'search_web_content': ['query', 'meta_access_token'],
 'send_capi_events': ['dataset_id',
                      'events',
                      'meta_access_token',
                      'test_event_code',
                      'auto_hash_user_data',
                      'partner_agent'],
 'suggest_interests': ['interest_list', 'meta_access_token', 'page_size', 'page_cursor'],
 'update_account_controls': ['ad_account_id',
                             'audience_controls',
                             'placement_controls',
                             'meta_access_token'],
 'update_ad': ['ad_id', 'status', 'bid_amount', 'tracking_specs', 'ad_creative_id', 'meta_access_token'],
 'update_ad_creative': ['ad_creative_id',
                        'meta_access_token',
                        'name',
                        'primary_text',
                        'primary_text_variants',
                        'headline_text',
                        'headline_variants',
                        'description_text',
                        'description_variants',
                        'optimization_type',
                        'dynamic_creative_spec',
                        'call_to_action_type',
                        'lead_form_id',
                        'ad_formats',
                        'destination_spec',
                        'degrees_of_freedom_spec',
                        'creative_features_spec'],
 'update_ad_set': ['ad_set_id',
                   'frequency_control_specs',
                   'bid_strategy',
                   'bid_amount',
                   'bid_constraints',
                   'status',
                   'targeting',
                   'optimization_goal',
                   'daily_budget',
                   'lifetime_budget',
                   'is_dynamic_creative',
                   'start_time',
                   'end_time',
                   'placement_soft_opt_out',
                   'attribution_spec',
                   'promoted_object',
                   'destination_type',
                   'dsa_beneficiary',
                   'dsa_payor',
                   'meta_access_token'],
 'update_campaign': ['campaign_id',
                     'meta_access_token',
                     'name',
                     'status',
                     'special_ad_categories',
                     'daily_budget',
                     'lifetime_budget',
                     'bid_strategy',
                     'bid_cap',
                     'spend_cap',
                     'campaign_budget_optimization',
                     'objective',
                     'use_ad_set_level_budgets',
                     'is_adset_budget_sharing_enabled',
                     'special_ad_category_country',
                     'migrate_to_advantage_plus',
                     'bid_constraints'],
 'update_custom_audience': ['custom_audience_id',
                            'meta_access_token',
                            'name',
                            'description',
                            'retention_days',
                            'rule',
                            'rule_aggregation'],
 'update_custom_conversion': ['custom_conversion_id',
                              'meta_access_token',
                              'name',
                              'description',
                              'rule',
                              'advanced_rule',
                              'custom_event_type',
                              'default_conversion_value'],
 'upload_ad_image_asset': ['ad_account_id', 'meta_access_token', 'image_file_path', 'image_source_url', 'name'],
 'upload_ad_video_asset': ['ad_account_id',
                           'meta_access_token',
                           'video_file_path',
                           'video_source_url',
                           'name',
                           'title',
                           'description'],
 'upsert_product': ['product_catalog_id', 'product', 'meta_access_token', 'allow_upsert']}
